spring:
  application:
    name: Automatizacion
  banner:
    location: templates/banner.txt
  config: #Configuraci√≥n de config server
    import: optional:configserver:http::localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8089
